apiVersion: v1
kind: ConfigMap
metadata:
  name: zewi-platform-config
  namespace: staging
data:
  config.yml: |
    app:
      name: zewi
      mode: prod
      port: 8001
      hostname: 0.0.0.0
      tls:
        status: off
        crt_path: cert/server.crt
        key_path: cert/server.key
      timeout: 50
      api_base_url: http://zewi-api:8002
      metrics:
        username: admin
        secret: secret
      log:
        level: info
        output: stdout
        format: json
      database:
        driver: postgresql
        host: localhost
        port: 5432
        username: postgres
        password: postgres
        name: zewi
        max_open_conns: 25
        max_idle_conns: 10
        conn_max_lifetime: 300
        datasource: ""
