apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zewi-ingress
  namespace: zewi
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: zewi.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zewi-platform
            port:
              number: 8000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: zewi-api
            port:
              number: 8001
