apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zewi-ingress
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: zewi.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zewi-landing
            port:
              number: 8000
  - host: platform.zewi.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zewi-platform
            port:
              number: 8001
  - host: api.zewi.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zewi-api
            port:
              number: 8002
