apiVersion: v1
kind: Secret
metadata:
  name: zewi-db-secret
  namespace: staging
type: Opaque
stringData:
  host: 127.0.0.1
  port: "5432"
  username: zewi
  password: zewi_pwd_ww3i3y
  database: zewi
