apiVersion: v1
kind: ConfigMap
metadata:
  name: zewi-hostname-config
  namespace: staging
data:
  config.yml: |
    app:
      name: zewi
      mode: prod
      port: 8003
      hostname: 0.0.0.0
      tls:
        status: off
        crt_path: cert/server.crt
        key_path: cert/server.key
      timeout: 50
      api_base_url: ""
      metrics:
        username: admin
        secret: secret
      log:
        level: info
        output: stdout
        format: json
