apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - namespace.yaml
  - configmap-staging-zewi-hostname.yaml
  - deployment-staging-zewi-hostname.yaml
  - service-staging-zewi-hostname.yaml
  - ingress.yaml
