apiVersion: v1
kind: Service
metadata:
  # http://zewi-hostname.staging.svc.cluster.local:8003/
  name: zewi-hostname
  namespace: staging
  labels:
    app: zewi-hostname
spec:
  type: ClusterIP
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
    name: http
  selector:
    app: zewi-hostname
